### ISSUE TITLE
Column with condition nvl(:REQUEST,'N') not like 'PLUGIN%' disappears after report refresh or change of the report page.

### ISSUE THREAD

**Issue by mihnea-gabur** [glebovpavel/IR_to_MSExcel#25]
I have a report with where I put the conditional display for a column: nvl(:REQUEST,'N') not like 'PLUGIN%'

If a refresh is triggered on the said report or if I change the report page the column with the condition disappears.

**Comment by glebovpavel** [comment]
Hi Mihnea,
Unfortunately i can't reproduce this error on apex.oracle.com.
(for example, on test app  https://apex.oracle.com/pls/apex/f?p=102065 )

Can you please write a detailed explanation (step by step) or make an example?

Regards, 
Pavel

**Comment by mihnea-gabur** [comment]
Hello, 
Here is the application example: https://apex.oracle.com/pls/apex/f?p=74088

On the second column (Cust first Name) I've put the condition nvl(:REQUEST,'N') not like 'PLUGIN%'

If I click the button IR refresh, the column disappears from the report.
The action of the button is a refresh of the report region.

Regards,
Mihnea

**Comment by glebovpavel** [comment]
Hi @mihnea-gabur 
Now in the least version you can use new function 
"not ir_to_msexcel.is_ir2msexcel"  expression to exclude column from export, 
and  "ir_to_msexcel.is_ir2msexcel" expression to make column visible on export only.
Old condition "nvl(:REQUEST,'N') not like 'PLUGIN%'" do not works in least APEX versions because all things (IR, IG etc...) are now actually plugins ...

Regards,
Pavel
